export const styles = {
  filterBlock:{
    height:70,
    flex:1,
    borderBottomWidth:2,
    borderBottomColor:'#ccc',
    flexWrap:'wrap'
  },
  search:{
    borderWidth:2,
    borderColor:'#ccc',
    margin:10,
    height:50,
    paddingLeft:10,
    borderRadius:5
  },
  filterHolders:{
    height:35,
    flexDirection:'row',
    marginHorizontal:10
  },
  filterOption:{
    flex:.5,
    flexDirection:'row'
  },
  radio:{
    height:25,
    width:25,
    borderRadius:32,
    borderWidth:2,
    borderColor:'#ccc',
    marginRight:10,
    marginTop:5
  },
  radioLabel:{
    fontSize:18,
    lineHeight:35
  },
  selected:{
    backgroundColor:'#ccc'
  }

}